services:
  postgres:
    environment:
      POSTGRES_DB: easyminer
      POSTGRES_PASSWORD: easyminer
      POSTGRES_USER: easyminer
    image: postgres:alpine
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
