apiVersion: v1
kind: Secret
metadata:
  name: {{ include "easyminer.fullname" . }}
  labels:
    {{- include "easyminer.labels" . | nindent 4 }}
type: Opaque
stringData:
  CELERY_BROKER: {{ include "easyminer.celeryBrokerUrl" . | quote }}
  CELERY_BACKEND: {{ include "easyminer.celeryBackendUrl" . | quote }}
  {{- if .Values.secrets.s3AccessKey }}
  S3_ACCESS_KEY: {{ .Values.secrets.s3AccessKey | quote }}
  S3_SECRET_KEY: {{ .Values.secrets.s3SecretKey | quote }}
  {{- end }}
