"""split field

Revision ID: 0b97e16f8684
Revises: 4255ef147722
Create Date: 2025-03-16 18:03:27.541953+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "0b97e16f8684"
down_revision: str | None = "4255ef147722"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "field_numeric_details",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.Column("min_value", sa.Double(), nullable=False),
        sa.Column("max_value", sa.Double(), nullable=False),
        sa.Column("avg_value", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(
            ["field_id"],
            ["field.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_field_numeric_details_id"),
        "field_numeric_details",
        ["id"],
        unique=False,
    )
    op.add_column("field", sa.Column("support", sa.Integer(), nullable=False))
    op.alter_column(
        "field",
        "data_type",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.Enum("nominal", "numeric", name="fieldtype"),
        existing_nullable=False,
    )
    op.drop_column("field", "has_nulls")
    op.drop_column("field", "index")
    op.drop_column("field", "missing_count")
    op.drop_column("field", "min_value")
    op.drop_column("field", "avg_value")
    op.drop_column("field", "max_value")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "field", sa.Column("max_value", mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column("field", sa.Column("avg_value", mysql.FLOAT(), nullable=True))
    op.add_column(
        "field", sa.Column("min_value", mysql.VARCHAR(length=255), nullable=True)
    )
    op.add_column(
        "field",
        sa.Column(
            "missing_count", mysql.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "field",
        sa.Column("index", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "field",
        sa.Column(
            "has_nulls",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.alter_column(
        "field",
        "data_type",
        existing_type=sa.Enum("nominal", "numeric", name="fieldtype"),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.drop_column("field", "support")
    op.drop_index(
        op.f("ix_field_numeric_details_id"), table_name="field_numeric_details"
    )
    op.drop_table("field_numeric_details")
    # ### end Alembic commands ###
