"""task status enum

Revision ID: 125057df0276
Revises: 0b97e16f8684
Create Date: 2025-03-18 21:07:22.417115+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "125057df0276"
down_revision: str | None = "0b97e16f8684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "field_numeric_details_ibfk_1", "field_numeric_details", type_="foreignkey"
    )
    op.drop_column("field_numeric_details", "field_id")
    op.alter_column(
        "task",
        "status",
        existing_type=mysql.VARCHAR(length=50),
        type_=sa.Enum("pending", "started", "success", "failure", name="taskstatus"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "status",
        existing_type=sa.Enum(
            "pending", "started", "success", "failure", name="taskstatus"
        ),
        type_=mysql.VARCHAR(length=50),
        existing_nullable=False,
    )
    op.add_column(
        "field_numeric_details",
        sa.Column("field_id", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "field_numeric_details_ibfk_1",
        "field_numeric_details",
        "field",
        ["field_id"],
        ["id"],
    )
    # ### end Alembic commands ###
