"""empty message

Revision ID: 1db430b25b30
Revises: xxxx
Create Date: 2025-03-12 17:16:04.047154+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1db430b25b30"
down_revision: str | None = "xxxx"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task",
        "task_id",
        existing_type=mysql.VARCHAR(length=36),
        type_=sa.Uuid(),
        existing_nullable=False,
    )
    op.add_column("upload", sa.Column("preview_max_lines", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("upload", "preview_max_lines")
    op.alter_column(
        "task",
        "task_id",
        existing_type=sa.Uuid(),
        type_=mysql.VARCHAR(length=36),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
