"""add chunk paths to db

Revision ID: 26c3c03c5b96
Revises: 9296b823465d
Create Date: 2025-03-16 10:46:49.648729+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "26c3c03c5b96"
down_revision: str | None = "9296b823465d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chunk",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["upload.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_id"), "chunk", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chunk_id"), table_name="chunk")
    op.drop_table("chunk")
    # ### end Alembic commands ###
