"""update field

Revision ID: 4255ef147722
Revises: 26c3c03c5b96
Create Date: 2025-03-16 11:26:22.802705+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4255ef147722"
down_revision: str | None = "26c3c03c5b96"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("field", sa.Column("missing_count", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("field", "missing_count")
    # ### end Alembic commands ###
