"""empty message

Revision ID: 8701e6c883ef
Revises: 0c02a101a25f
Create Date: 2025-02-10 23:53:19.944244+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8701e6c883ef"
down_revision: str | None = "0c02a101a25f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("media_type", sa.String(length=20), nullable=False),
        sa.Column("db_type", sa.String(length=20), nullable=False),
        sa.Column("separator", sa.String(length=1), nullable=False),
        sa.Column("encoding", sa.String(length=40), nullable=False),
        sa.Column("quotes_char", sa.String(length=1), nullable=False),
        sa.Column("escape_char", sa.String(length=1), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("compression", sa.String(length=20), nullable=False),
        sa.Column("format", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_upload_id"), "upload", ["id"], unique=False)
    op.create_table(
        "upload_data_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_data_types_id"), "upload_data_types", ["id"], unique=False
    )
    op.create_table(
        "upload_null_value",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_null_value_id"), "upload_null_value", ["id"], unique=False
    )
    op.create_table(
        "upload_data_type_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=True),
        sa.Column("upload_data_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["upload_data_type_id"],
            ["upload_data_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["upload.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_data_type_table_id"),
        "upload_data_type_table",
        ["id"],
        unique=False,
    )
    op.create_table(
        "upload_null_value_table",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=True),
        sa.Column("upload_null_value_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["upload_id"],
            ["upload.id"],
        ),
        sa.ForeignKeyConstraint(
            ["upload_null_value_id"],
            ["upload_null_value.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_upload_null_value_table_id"),
        "upload_null_value_table",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_upload_null_value_table_id"), table_name="upload_null_value_table"
    )
    op.drop_table("upload_null_value_table")
    op.drop_index(
        op.f("ix_upload_data_type_table_id"), table_name="upload_data_type_table"
    )
    op.drop_table("upload_data_type_table")
    op.drop_index(op.f("ix_upload_null_value_id"), table_name="upload_null_value")
    op.drop_table("upload_null_value")
    op.drop_index(op.f("ix_upload_data_types_id"), table_name="upload_data_types")
    op.drop_table("upload_data_types")
    op.drop_index(op.f("ix_upload_id"), table_name="upload")
    op.drop_table("upload")
    # ### end Alembic commands ###
