"""require upload id for datasource

Revision ID: 9296b823465d
Revises: 47e05a04ad3b
Create Date: 2025-03-16 10:44:15.081299+01:00

"""

from collections.abc import Sequence

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "9296b823465d"
down_revision: str | None = "47e05a04ad3b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "upload", "compression", existing_type=mysql.VARCHAR(length=20), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "upload", "compression", existing_type=mysql.VARCHAR(length=20), nullable=False
    )
    # ### end Alembic commands ###
