"""init

Revision ID: dca96f819673
Revises:
Create Date: 2025-04-10 22:54:15.691978+02:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dca96f819673"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_source",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.Enum("limited", name="dbtype"), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_finished", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_result",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("type", sa.Enum("limited", name="dbtype"), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.Enum("nominal", "numeric", name="fieldtype"), nullable=False),
        sa.Column("unique_values_size_nominal", sa.Integer(), nullable=False),
        sa.Column("unique_values_size_numeric", sa.Integer(), nullable=False),
        sa.Column("support_nominal", sa.Integer(), nullable=False),
        sa.Column("support_numeric", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "preview_upload",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("max_lines", sa.Integer(), nullable=False),
        sa.Column("compression", sa.Enum("zip", "gzip", "bzip2", name="compressiontype"), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("task_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "scheduled", "started", "success", "failure", name="taskstatusenum"),
            nullable=False,
        ),
        sa.Column("status_message", sa.String(length=255), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=True),
        sa.Column("result_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["result_id"], ["task_result.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_task_id"), "task", ["task_id"], unique=True)
    op.create_table(
        "upload",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("media_type", sa.Enum("csv", name="mediatype"), nullable=False),
        sa.Column("db_type", sa.Enum("limited", name="dbtype"), nullable=False),
        sa.Column("separator", sa.String(length=1), nullable=False),
        sa.Column("encoding", sa.String(length=40), nullable=False),
        sa.Column("quotes_char", sa.String(length=1), nullable=False),
        sa.Column("escape_char", sa.String(length=1), nullable=False),
        sa.Column("locale", sa.String(length=20), nullable=False),
        sa.Column("compression", sa.Enum("zip", "gzip", "bzip2", name="compressiontype"), nullable=True),
        sa.Column("preview_max_lines", sa.Integer(), nullable=True),
        sa.Column("null_values", sa.ARRAY(sa.String(length=255)), nullable=False),
        sa.Column("data_types", sa.ARRAY(sa.Enum("nominal", "numeric", name="fieldtype")), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_source_id"),
    )
    op.create_table(
        "chunk",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("upload_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["upload_id"], ["upload.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_source_instance",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("row_id", sa.Integer(), nullable=False),
        sa.Column("value_nominal", sa.String(length=255), nullable=True),
        sa.Column("value_numeric", sa.Double(), nullable=True),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_source_value",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value_nominal", sa.String(length=255), nullable=True),
        sa.Column("value_numeric", sa.Double(), nullable=True),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("data_source_id", sa.Integer(), nullable=False),
        sa.Column("field_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_source.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["field_id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "field_numeric_detail",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("min_value", sa.Double(), nullable=False),
        sa.Column("max_value", sa.Double(), nullable=False),
        sa.Column("avg_value", sa.Double(), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["field.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("field_numeric_detail")
    op.drop_table("data_source_value")
    op.drop_table("data_source_instance")
    op.drop_table("chunk")
    op.drop_table("upload")
    op.drop_index(op.f("ix_task_task_id"), table_name="task")
    op.drop_table("task")
    op.drop_table("preview_upload")
    op.drop_table("field")
    op.drop_table("dataset")
    op.drop_table("task_result")
    op.drop_table("data_source")
    # ### end Alembic commands ###
