"""fix_upload_relationships

Revision ID: de8f6c25a351
Revises: 14b401bfe2db
Create Date: 2025-02-23 14:53:11.710042+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'de8f6c25a351'
down_revision: str | None = '14b401bfe2db'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
