"""datasource is_finished

Revision ID: eed37fc0c4d4
Revises: 4e985fe85307
Create Date: 2025-03-26 22:47:56.723741+01:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eed37fc0c4d4"
down_revision: str | None = "4e985fe85307"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("data_source", sa.Column("is_finished", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_source", "is_finished")
    # ### end Alembic commands ###
